//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LocalizedText", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered Access Card Number Already Exists in Access Card Inventory!.
        /// </summary>
        internal static string AccessCardCheck {
            get {
                return ResourceManager.GetString("AccessCardCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Access card custodian is mapped to this facility.Kindly map and then try to close the request..
        /// </summary>
        internal static string accesscardcustodianmsg {
            get {
                return ResourceManager.GetString("accesscardcustodianmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Access Card is Generated Successfully.
        /// </summary>
        internal static string AccessCardGenerated {
            get {
                return ResourceManager.GetString("AccessCardGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Access Card No.
        /// </summary>
        internal static string AccessCardNo {
            get {
                return ResourceManager.GetString("AccessCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Access Card Returned successfully for the Associate.
        /// </summary>
        internal static string AccessCardReturned {
            get {
                return ResourceManager.GetString("AccessCardReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Out Time.
        /// </summary>
        internal static string ActualOutTime {
            get {
                return ResourceManager.GetString("ActualOutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter either Associate Id or Associate Name.
        /// </summary>
        internal static string AssociateDetailsPopUpCaption {
            get {
                return ResourceManager.GetString("AssociateDetailsPopUpCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate ID.
        /// </summary>
        internal static string AssociateId {
            get {
                return ResourceManager.GetString("AssociateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate List.
        /// </summary>
        internal static string AssociateList {
            get {
                return ResourceManager.GetString("AssociateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate Name.
        /// </summary>
        internal static string AssociateName {
            get {
                return ResourceManager.GetString("AssociateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facility Name :.
        /// </summary>
        internal static string BadgeFacility {
            get {
                return ResourceManager.GetString("BadgeFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge Lost. Check Out Successful..
        /// </summary>
        internal static string BadgeLost {
            get {
                return ResourceManager.GetString("BadgeLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge No.
        /// </summary>
        internal static string BadgeNo {
            get {
                return ResourceManager.GetString("BadgeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge Returned. Check Out Successful..
        /// </summary>
        internal static string BadgeReturned {
            get {
                return ResourceManager.GetString("BadgeReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string BadgeStatus {
            get {
                return ResourceManager.GetString("BadgeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge status update.
        /// </summary>
        internal static string BadgeStatusUpdate {
            get {
                return ResourceManager.GetString("BadgeStatusUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Group #:.
        /// </summary>
        internal static string BloodGroup {
            get {
                return ResourceManager.GetString("BloodGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Requests.
        /// </summary>
        internal static string btnBackToRequests {
            get {
                return ResourceManager.GetString("btnBackToRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string btnConfirm {
            get {
                return ResourceManager.GetString("btnConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string btnExport {
            get {
                return ResourceManager.GetString("btnExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string btnNo {
            get {
                return ResourceManager.GetString("btnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string btnView {
            get {
                return ResourceManager.GetString("btnView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string btnYes {
            get {
                return ResourceManager.GetString("btnYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel?.
        /// </summary>
        internal static string CancelConfirmation {
            get {
                return ResourceManager.GetString("CancelConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Details.
        /// </summary>
        internal static string CardInformation {
            get {
                return ResourceManager.GetString("CardInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Log.
        /// </summary>
        internal static string CardLog {
            get {
                return ResourceManager.GetString("CardLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check In.
        /// </summary>
        internal static string CheckIn {
            get {
                return ResourceManager.GetString("CheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out.
        /// </summary>
        internal static string CheckOut {
            get {
                return ResourceManager.GetString("CheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout option is available in table. Please refer the bottom of the page..
        /// </summary>
        internal static string Checkoutbuttonmsg {
            get {
                return ResourceManager.GetString("Checkoutbuttonmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        internal static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City :.
        /// </summary>
        internal static string CityIVS {
            get {
                return ResourceManager.GetString("CityIVS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cognizant Technology Solutions.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Address  while visiting.
        /// </summary>
        internal static string ContactAddress {
            get {
                return ResourceManager.GetString("ContactAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From time should be greater than or equal to current time..
        /// </summary>
        internal static string CurrentTimeError {
            get {
                return ResourceManager.GetString("CurrentTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Time should be greater than From Time.
        /// </summary>
        internal static string CurrentTimeFromTimeToTime {
            get {
                return ResourceManager.GetString("CurrentTimeFromTimeToTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a date within 7 days from today.
        /// </summary>
        internal static string DateRange {
            get {
                return ResourceManager.GetString("DateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date has to be greater than From Date.
        /// </summary>
        internal static string DateValid {
            get {
                return ResourceManager.GetString("DateValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days in advance..
        /// </summary>
        internal static string DayInAdvance {
            get {
                return ResourceManager.GetString("DayInAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation.
        /// </summary>
        internal static string Designation {
            get {
                return ResourceManager.GetString("Designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer : By returning this token I hereby confirm that I have received the asset.
        /// </summary>
        internal static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to described here..
        /// </summary>
        internal static string DisclaimerNext {
            get {
                return ResourceManager.GetString("DisclaimerNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor Information already available.
        /// </summary>
        internal static string DuplicateVisitor {
            get {
                return ResourceManager.GetString("DuplicateVisitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid Email ID.
        /// </summary>
        internal static string EmailCheck {
            get {
                return ResourceManager.GetString("EmailCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ID.
        /// </summary>
        internal static string EmailID {
            get {
                return ResourceManager.GetString("EmailID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Contact #:.
        /// </summary>
        internal static string EmercengyContact {
            get {
                return ResourceManager.GetString("EmercengyContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Contact From Date and To Date should not be lesser than Current Date..
        /// </summary>
        internal static string EmergencyContactTime {
            get {
                return ResourceManager.GetString("EmergencyContactTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter AssociateID.
        /// </summary>
        internal static string EnterAssociateId {
            get {
                return ResourceManager.GetString("EnterAssociateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter First Name.
        /// </summary>
        internal static string EnterFirstName {
            get {
                return ResourceManager.GetString("EnterFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Last Name.
        /// </summary>
        internal static string EnterLastName {
            get {
                return ResourceManager.GetString("EnterLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Mobile.
        /// </summary>
        internal static string EnterMobile {
            get {
                return ResourceManager.GetString("EnterMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Permitted.
        /// </summary>
        internal static string EquipmentPermitted {
            get {
                return ResourceManager.GetString("EquipmentPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Type.
        /// </summary>
        internal static string EquipmentType {
            get {
                return ResourceManager.GetString("EquipmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while processing your request..
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error has occured while checking out..
        /// </summary>
        internal static string ErrorMessageCheckOut {
            get {
                return ResourceManager.GetString("ErrorMessageCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected In Time.
        /// </summary>
        internal static string ExpectedInTime {
            get {
                return ResourceManager.GetString("ExpectedInTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        internal static string Extension {
            get {
                return ResourceManager.GetString("Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facility Name.
        /// </summary>
        internal static string Facility {
            get {
                return ResourceManager.GetString("Facility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facility Name :.
        /// </summary>
        internal static string FacilityIVS {
            get {
                return ResourceManager.GetString("FacilityIVS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facility .
        /// </summary>
        internal static string FacilityName {
            get {
                return ResourceManager.GetString("FacilityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facility.
        /// </summary>
        internal static string FaciltyCardReturn {
            get {
                return ResourceManager.GetString("FaciltyCardReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Card.
        /// </summary>
        internal static string ForgotIDCard {
            get {
                return ResourceManager.GetString("ForgotIDCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        internal static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date should be less than or equal to To Date..
        /// </summary>
        internal static string FromDateValidation {
            get {
                return ResourceManager.GetString("FromDateValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Time.
        /// </summary>
        internal static string FromTime {
            get {
                return ResourceManager.GetString("FromTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to generate badge?.
        /// </summary>
        internal static string GenerateBadge {
            get {
                return ResourceManager.GetString("GenerateBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Badge.
        /// </summary>
        internal static string GenerateBadgeRequest {
            get {
                return ResourceManager.GetString("GenerateBadgeRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        internal static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Contact Number.
        /// </summary>
        internal static string HostContactNumber {
            get {
                return ResourceManager.GetString("HostContactNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Signature :.
        /// </summary>
        internal static string HostSignature {
            get {
                return ResourceManager.GetString("HostSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary  ID Card and Access Card is Generated Successfully.
        /// </summary>
        internal static string IDCardandAccessCardGenerated {
            get {
                return ResourceManager.GetString("IDCardandAccessCardGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary  ID Card and Access Card Returned successfully for the Associate.
        /// </summary>
        internal static string IDCardandAccessCardReturned {
            get {
                return ResourceManager.GetString("IDCardandAccessCardReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To View the calender control.
        /// </summary>
        internal static string imgcalenderControl {
            get {
                return ResourceManager.GetString("imgcalenderControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        internal static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindly use only &quot; Lost&quot; function for InActive Associates .
        /// </summary>
        internal static string InactiveMsg {
            get {
                return ResourceManager.GetString("InactiveMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Date.
        /// </summary>
        internal static string InDate {
            get {
                return ResourceManager.GetString("InDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Time.
        /// </summary>
        internal static string InTime {
            get {
                return ResourceManager.GetString("InTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate ID does not exist..
        /// </summary>
        internal static string InValidAssociateId {
            get {
                return ResourceManager.GetString("InValidAssociateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Time.
        /// </summary>
        internal static string InvalidTime {
            get {
                return ResourceManager.GetString("InvalidTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued.
        /// </summary>
        internal static string Issued {
            get {
                return ResourceManager.GetString("Issued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Temporary Card.
        /// </summary>
        internal static string IssueTemporaryCard {
            get {
                return ResourceManager.GetString("IssueTemporaryCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IVS.
        /// </summary>
        internal static string IVS {
            get {
                return ResourceManager.GetString("IVS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindly follow the instructions provided on the reverse.
        /// </summary>
        internal static string KindlyFollow {
            get {
                return ResourceManager.GetString("KindlyFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inside the Premises.
        /// </summary>
        internal static string lblAmber {
            get {
                return ResourceManager.GetString("lblAmber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Pin Code, Country.
        /// </summary>
        internal static string lblArea {
            get {
                return ResourceManager.GetString("lblArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note&amp;nbsp;:&amp;nbsp;&amp;nbsp;Please return this badge at the security before leaving this premises.
        /// </summary>
        internal static string lblBadgeNote {
            get {
                return ResourceManager.GetString("lblBadgeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved. Powered By IT.&lt;br&gt;Recommended viewing in Internet Explorer 7.0 or higher at 1024 X 768 and above resolution..
        /// </summary>
        internal static string lblBottomCaption {
            get {
                return ResourceManager.GetString("lblBottomCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There hasn&apos;t been any ODI Card issued today.
        /// </summary>
        internal static string lblCardNoIssuedAlert {
            get {
                return ResourceManager.GetString("lblCardNoIssuedAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error has occured while checking out..
        /// </summary>
        internal static string lblCheckoutError {
            get {
                return ResourceManager.GetString("lblCheckoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Here.
        /// </summary>
        internal static string lblClickHere {
            get {
                return ResourceManager.GetString("lblClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you verified associate’s identity to be same as IVS badge being generated?.
        /// </summary>
        internal static string lblCommitting {
            get {
                return ResourceManager.GetString("lblCommitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you verified if associate does not have permanent access card?.
        /// </summary>
        internal static string lblCommitting1 {
            get {
                return ResourceManager.GetString("lblCommitting1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you verified if associate does not have permanent access card &amp; identity to be same as IVS badge being generated?.
        /// </summary>
        internal static string lblCommitting2 {
            get {
                return ResourceManager.GetString("lblCommitting2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If yes, click on &apos;Confirm&apos; else click on &apos;Go Back&apos; ..
        /// </summary>
        internal static string lblConfirm {
            get {
                return ResourceManager.GetString("lblConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Contact in Visiting City.
        /// </summary>
        internal static string lblEmergencyContact {
            get {
                return ResourceManager.GetString("lblEmergencyContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In case of any emergency please contact the security at.
        /// </summary>
        internal static string lblEmergencyContactInstr {
            get {
                return ResourceManager.GetString("lblEmergencyContactInstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Details.
        /// </summary>
        internal static string lblEmployeeHeader {
            get {
                return ResourceManager.GetString("lblEmployeeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string lblEmployeeID {
            get {
                return ResourceManager.GetString("lblEmployeeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODI #.
        /// </summary>
        internal static string lblEmpPass {
            get {
                return ResourceManager.GetString("lblEmpPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Number:.
        /// </summary>
        internal static string lblEquipmentCust {
            get {
                return ResourceManager.GetString("lblEquipmentCust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipments In Custody.
        /// </summary>
        internal static string lblEquipmentsCustody {
            get {
                return ResourceManager.GetString("lblEquipmentsCustody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipments Permitted.
        /// </summary>
        internal static string lblEquipmentsPermitted {
            get {
                return ResourceManager.GetString("lblEquipmentsPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EquipmentType.
        /// </summary>
        internal static string lblEquipmentType {
            get {
                return ResourceManager.GetString("lblEquipmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceeds Expected Out Time.
        /// </summary>
        internal static string lblExceedOutTime {
            get {
                return ResourceManager.GetString("lblExceedOutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Out Time.
        /// </summary>
        internal static string lblExpectedOutTime {
            get {
                return ResourceManager.GetString("lblExpectedOutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Express Check-In No.
        /// </summary>
        internal static string lblExpressCheckin {
            get {
                return ResourceManager.GetString("lblExpressCheckin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful check out..
        /// </summary>
        internal static string lblGreen {
            get {
                return ResourceManager.GetString("lblGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information !.
        /// </summary>
        internal static string lblInformation {
            get {
                return ResourceManager.GetString("lblInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Check In Code.
        /// </summary>
        internal static string lblInvalidCheckinCode {
            get {
                return ResourceManager.GetString("lblInvalidCheckinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        internal static string lblLegend {
            get {
                return ResourceManager.GetString("lblLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Details.
        /// </summary>
        internal static string lblManagerHeader {
            get {
                return ResourceManager.GetString("lblManagerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Temporary ID Card.
        /// </summary>
        internal static string lblModuleValue {
            get {
                return ResourceManager.GetString("lblModuleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Relevant Requests?.
        /// </summary>
        internal static string lblNoRelevantRequest {
            get {
                return ResourceManager.GetString("lblNoRelevantRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindly ensure that you have checked all the security desk at your facility  for the returned Temp ID card of the associate.
        /// </summary>
        internal static string lblReminderCommitting {
            get {
                return ResourceManager.GetString("lblReminderCommitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the last reminder mail. Kindly cross check at all security desk for the returned temp ID card of the associate.
        /// </summary>
        internal static string lblReminderCommitting2 {
            get {
                return ResourceManager.GetString("lblReminderCommitting2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Safety Permit Id.
        /// </summary>
        internal static string lblSafetyPermitId {
            get {
                return ResourceManager.GetString("lblSafetyPermitId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (OR).
        /// </summary>
        internal static string lblSearchOR {
            get {
                return ResourceManager.GetString("lblSearchOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Name,Company,Badge number.
        /// </summary>
        internal static string lblSearchSafetyPermit {
            get {
                return ResourceManager.GetString("lblSearchSafetyPermit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security ID is not tagged to a Facility.
        /// </summary>
        internal static string lblSecurityInValid {
            get {
                return ResourceManager.GetString("lblSecurityInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEMPORARY IDENTITY CARD.
        /// </summary>
        internal static string lblTempId {
            get {
                return ResourceManager.GetString("lblTempId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid Date in the ToDate field.
        /// </summary>
        internal static string lblTodateMandatory {
            get {
                return ResourceManager.GetString("lblTodateMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid Date in the &apos;ToDate&apos; field.
        /// </summary>
        internal static string lblToDateValidation {
            get {
                return ResourceManager.GetString("lblToDateValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Number:.
        /// </summary>
        internal static string lbltokenNumber {
            get {
                return ResourceManager.GetString("lbltokenNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALID FROM.
        /// </summary>
        internal static string lblValidfrom {
            get {
                return ResourceManager.GetString("lblValidfrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALID TO.
        /// </summary>
        internal static string lblValidTo {
            get {
                return ResourceManager.GetString("lblValidTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Visitor is yet to surrender the following visitor card(s) issued earlier..
        /// </summary>
        internal static string lblVCard {
            get {
                return ResourceManager.GetString("lblVCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you visited any of the Cognizant facilities before?.
        /// </summary>
        internal static string lblVisit {
            get {
                return ResourceManager.GetString("lblVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string LocationCard {
            get {
                return ResourceManager.GetString("LocationCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        internal static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log View.
        /// </summary>
        internal static string LogView {
            get {
                return ResourceManager.GetString("LogView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost.
        /// </summary>
        internal static string Lost {
            get {
                return ResourceManager.GetString("Lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make.
        /// </summary>
        internal static string Make {
            get {
                return ResourceManager.GetString("Make", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates Mandatory Field.
        /// </summary>
        internal static string MandatoryField {
            get {
                return ResourceManager.GetString("MandatoryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Entries.
        /// </summary>
        internal static string MultipleEntries {
            get {
                return ResourceManager.GetString("MultipleEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native Country.
        /// </summary>
        internal static string NativeCountry {
            get {
                return ResourceManager.GetString("NativeCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Equipment Permitted.
        /// </summary>
        internal static string NoEquipmentPermitted {
            get {
                return ResourceManager.GetString("NoEquipmentPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no open requests with the Check In Code entered for this facility.
        /// </summary>
        internal static string NoOpenRequest {
            get {
                return ResourceManager.GetString("NoOpenRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Records Found.
        /// </summary>
        internal static string NoRecordFound {
            get {
                return ResourceManager.GetString("NoRecordFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate has been issued with selected Card..
        /// </summary>
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PS offered in:.
        /// </summary>
        internal static string OfferedLanguage {
            get {
                return ResourceManager.GetString("OfferedLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onsite Return.
        /// </summary>
        internal static string OnsiteReturn {
            get {
                return ResourceManager.GetString("OnsiteReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        internal static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If Others Specify.
        /// </summary>
        internal static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out.
        /// </summary>
        internal static string Out {
            get {
                return ResourceManager.GetString("Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Date.
        /// </summary>
        internal static string OutDate {
            get {
                return ResourceManager.GetString("OutDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Time.
        /// </summary>
        internal static string OutTime {
            get {
                return ResourceManager.GetString("OutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please refer the table at bottom of the page for the options (Check out / Lost / Reprint / View / Reminder Mail) to process one day id/access card requests.
        /// </summary>
        internal static string Pendingrequest {
            get {
                return ResourceManager.GetString("Pendingrequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer Jammed.
        /// </summary>
        internal static string PrinterJammed {
            get {
                return ResourceManager.GetString("PrinterJammed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PurposeList&gt;&lt;Purpose text=&quot;Select Purpose&quot; value=&quot;Select&quot;/&gt;
        ///  &lt;Purpose text=&quot;Client&quot; value=&quot;Client&quot;/&gt;
        ///  &lt;Purpose text=&quot;Vendor&quot; value=&quot;Vendor&quot;/&gt;
        ///  &lt;Purpose text=&quot;Family Members&quot; value=&quot;Family Members&quot;/&gt;
        ///  &lt;Purpose text=&quot;Imp/VIP Visitor&quot; value=&quot;Imp/VIP Visitor&quot;/&gt;
        ///  &lt;Purpose text=&quot;Interview Candidate&quot; value=&quot;Interview Candidate&quot;/&gt;
        ///  &lt;Purpose text=&quot;Others&quot; value=&quot;Others&quot;/&gt; 
        ///&lt;/PurposeList&gt;.
        /// </summary>
        internal static string PurposeList {
            get {
                return ResourceManager.GetString("PurposeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason :.
        /// </summary>
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Date.
        /// </summary>
        internal static string RefreshDate {
            get {
                return ResourceManager.GetString("RefreshDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Issue.
        /// </summary>
        internal static string ReIssue {
            get {
                return ResourceManager.GetString("ReIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder Mail 1.
        /// </summary>
        internal static string ReminderMail {
            get {
                return ResourceManager.GetString("ReminderMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder Mail has been sent to the Associate.
        /// </summary>
        internal static string ReminderNotification {
            get {
                return ResourceManager.GetString("ReminderNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re print.
        /// </summary>
        internal static string Reprint {
            get {
                return ResourceManager.GetString("Reprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprint option is available in table. Please refer the bottom of the page..
        /// </summary>
        internal static string Reprintbuttonmsg {
            get {
                return ResourceManager.GetString("Reprintbuttonmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReprintComments.
        /// </summary>
        internal static string ReprintComments {
            get {
                return ResourceManager.GetString("ReprintComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprint successful..
        /// </summary>
        internal static string Reprintsuccessful {
            get {
                return ResourceManager.GetString("Reprintsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Native country.
        /// </summary>
        internal static string ReqNativecountry {
            get {
                return ResourceManager.GetString("ReqNativecountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests are allowed to raise for only.
        /// </summary>
        internal static string RequestallowedCheck {
            get {
                return ResourceManager.GetString("RequestallowedCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request is not cancelled..
        /// </summary>
        internal static string Requestnotcancelled {
            get {
                return ResourceManager.GetString("Requestnotcancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter From Date.
        /// </summary>
        internal static string RequiredFromDate {
            get {
                return ResourceManager.GetString("RequiredFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter To Date.
        /// </summary>
        internal static string RequiredToDate {
            get {
                return ResourceManager.GetString("RequiredToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned.
        /// </summary>
        internal static string Returned {
            get {
                return ResourceManager.GetString("Returned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Successfully for future Submission.
        /// </summary>
        internal static string SavedForFutureSubmission {
            get {
                return ResourceManager.GetString("SavedForFutureSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Name, Vcard, Organization, Mobile No.
        /// </summary>
        internal static string searchByName {
            get {
                return ResourceManager.GetString("searchByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Name, Organization, Mobile No.
        /// </summary>
        internal static string searchByNameOld {
            get {
                return ResourceManager.GetString("searchByNameOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search HostName.
        /// </summary>
        internal static string SearchHostName {
            get {
                return ResourceManager.GetString("SearchHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search User Details.
        /// </summary>
        internal static string SearchUserDetails {
            get {
                return ResourceManager.GetString("SearchUserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select City.
        /// </summary>
        internal static string SelectCity {
            get {
                return ResourceManager.GetString("SelectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Country.
        /// </summary>
        internal static string SelectCountry {
            get {
                return ResourceManager.GetString("SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select any of the Equipment Type.
        /// </summary>
        internal static string SelectEquipmentType {
            get {
                return ResourceManager.GetString("SelectEquipmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Host.
        /// </summary>
        internal static string SelectHost {
            get {
                return ResourceManager.GetString("SelectHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a reason.
        /// </summary>
        internal static string SelectReason {
            get {
                return ResourceManager.GetString("SelectReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a comment for reprinting the badge.
        /// </summary>
        internal static string SelectReprintCommand {
            get {
                return ResourceManager.GetString("SelectReprintCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select atleast one search option.
        /// </summary>
        internal static string Selectsearch {
            get {
                return ResourceManager.GetString("Selectsearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Status.
        /// </summary>
        internal static string SelectStatus {
            get {
                return ResourceManager.GetString("SelectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Visitor Type.
        /// </summary>
        internal static string SelectVisitorType {
            get {
                return ResourceManager.GetString("SelectVisitorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial No.
        /// </summary>
        internal static string SerialNo {
            get {
                return ResourceManager.GetString("SerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sl.no.
        /// </summary>
        internal static string SlNo {
            get {
                return ResourceManager.GetString("SlNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Submit a Request.
        /// </summary>
        internal static string SubmitMandatory {
            get {
                return ResourceManager.GetString("SubmitMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted Successfully..
        /// </summary>
        internal static string SubmittedSuccessfully {
            get {
                return ResourceManager.GetString("SubmittedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor request has been submitted successfully.
        /// </summary>
        internal static string SubmitVisitorRequest {
            get {
                return ResourceManager.GetString("SubmitVisitorRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary ID Card is generated Successfully.
        /// </summary>
        internal static string TempCardGenerated {
            get {
                return ResourceManager.GetString("TempCardGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary ID card Returned successfully for the Associate.
        /// </summary>
        internal static string TempCardReturned {
            get {
                return ResourceManager.GetString("TempCardReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This associate is no longer with Cognizant..
        /// </summary>
        internal static string TerminatedMessage {
            get {
                return ResourceManager.GetString("TerminatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time :.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time is not entered.
        /// </summary>
        internal static string TimeEmpty {
            get {
                return ResourceManager.GetString("TimeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Extended Successfully..
        /// </summary>
        internal static string TimeExtend {
            get {
                return ResourceManager.GetString("TimeExtend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        internal static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Time.
        /// </summary>
        internal static string ToTime {
            get {
                return ResourceManager.GetString("ToTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under.
        /// </summary>
        internal static string Under {
            get {
                return ResourceManager.GetString("Under", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Successfully..
        /// </summary>
        internal static string UpdatedSuccessfully {
            get {
                return ResourceManager.GetString("UpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updation Failed.
        /// </summary>
        internal static string UpdationFailed {
            get {
                return ResourceManager.GetString("UpdationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload &amp; Close.
        /// </summary>
        internal static string UploadAndClose {
            get {
                return ResourceManager.GetString("UploadAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Photo.
        /// </summary>
        internal static string UploadPhoto {
            get {
                return ResourceManager.GetString("UploadPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCard #.
        /// </summary>
        internal static string VCard {
            get {
                return ResourceManager.GetString("VCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor has been checked out successfully.
        /// </summary>
        internal static string VCardReturned {
            get {
                return ResourceManager.GetString("VCardReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        internal static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit duration should be less than or equal to .
        /// </summary>
        internal static string VisitDurationError {
            get {
                return ResourceManager.GetString("VisitDurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string VisitDurationErrorday {
            get {
                return ResourceManager.GetString("VisitDurationErrorday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit From Date should be greater than or equal to current date.
        /// </summary>
        internal static string VisitFromTimeMandatory {
            get {
                return ResourceManager.GetString("VisitFromTimeMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Location Information.
        /// </summary>
        internal static string VisitLocationInformation {
            get {
                return ResourceManager.GetString("VisitLocationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Visitor Badge is successfully generated..
        /// </summary>
        internal static string VisitorBadgeGenerated {
            get {
                return ResourceManager.GetString("VisitorBadgeGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor has been checked in successfully.
        /// </summary>
        internal static string Visitorcheckinsuccessful {
            get {
                return ResourceManager.GetString("Visitorcheckinsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor Id.
        /// </summary>
        internal static string VisitorId {
            get {
                return ResourceManager.GetString("VisitorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor Image.
        /// </summary>
        internal static string VisitorImage {
            get {
                return ResourceManager.GetString("VisitorImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor Information.
        /// </summary>
        internal static string VisitorInformation {
            get {
                return ResourceManager.GetString("VisitorInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitors Pass # :.
        /// </summary>
        internal static string VisitorsPass {
            get {
                return ResourceManager.GetString("VisitorsPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor Type.
        /// </summary>
        internal static string VisitorType {
            get {
                return ResourceManager.GetString("VisitorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit From Date and Visit To Date should be greater than or equal to current date.
        /// </summary>
        internal static string VisitTimeMandatory {
            get {
                return ResourceManager.GetString("VisitTimeMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit To Date should be greater than or equal to current date.
        /// </summary>
        internal static string VisitToTimeMandatory {
            get {
                return ResourceManager.GetString("VisitToTimeMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VMS.
        /// </summary>
        internal static string VMS {
            get {
                return ResourceManager.GetString("VMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Cam.
        /// </summary>
        internal static string WebCam {
            get {
                return ResourceManager.GetString("WebCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yet to arrive.
        /// </summary>
        internal static string Yettoarrive {
            get {
                return ResourceManager.GetString("Yettoarrive", resourceCulture);
            }
        }
    }
}
